name: airport_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  awesome: ^0.0.3
  awesome_dialog: ^3.2.1
  country_phone_validator: ^1.0.1
  dialog: ^0.8.0
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_multi_formatter: ^2.13.9
  http: ^1.4.0
  intl: ^0.20.2
  percent_indicator: ^4.2.5
  shimmer_animation: ^2.2.2
  syncfusion_flutter_datagrid: ^31.1.19
  syncfusion_flutter_datepicker: ^31.1.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
