name: airport_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  datepicker_dropdown: ^0.1.7
  flutter:
    sdk: flutter
  http: ^1.4.0
  intl: ^0.20.2
  syncfusion_flutter_datepicker: ^30.1.42

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
